Work/Work/Models/CartShop.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Work.Models
{
    public class CartShop
    {
        public int orderID { get; set; }
        public int userID { get; set; }
        public int deliveryID { get; set; }
        public int paymentID { get; set; }
        public DateTime orderDate { get; set; }
        public DateTime deliveryDate { get; set; }
        public string shipAddress { get; set; }

        public SortedList<string, bill> orderedProduct { get; set; }

        public int cartItem()
        {
            return (int)orderedProduct.Values.Sum(s => s.quantity);
        }

        public CartShop()
        {
            this.orderID = 0;
            this.userID = 0;
            this.deliveryID = 0;
            this.paymentID = 0;
            this.shipAddress = "";
            this.orderDate = DateTime.Now;
            this.deliveryDate = DateTime.Now.AddDays(3);
            this.orderedProduct = new SortedList<string, bill>();
        }

        public bool IsEmpty()
        {
            return orderedProduct.Keys.Count == 0;
        }

        public void addItem(string productID)
        {
            if (orderedProduct.Keys.Contains(productID))
            {
                bill b = orderedProduct.Values[orderedProduct.IndexOfKey(productID)];
                b.quantity++;
            }
            else
            {
                bill b = new bill();
                b.productID = productID;
                b.quantity = 1;
                product p = Common.GetProductById(productID);
                b.price = p.price;
                b.discount = p.sale;
                orderedProduct.Add(productID, b);
            }
        }

        public void deleteItem(string productID)
        {
            if (orderedProduct.Keys.Contains(productID))
            {
                orderedProduct.Remove(productID);
            }
        }

        public void decrease(string productID)
        {
            if (orderedProduct.Keys.Contains(productID))
            {
                bill b = orderedProduct.Values[orderedProduct.IndexOfKey((string)productID)];
                if (b.quantity > 1)
                {
                    b.quantity--;
                }
                else
                {
                    deleteItem(productID);
                }
            }
        }

        public long moneyOfOneProduct(bill b)
        {
            return (long)((b.quantity * b.price) - (b.quantity * b.price * b.discount));
        }

        public long totalOfCartShop()
        {
            long total = 0;
            foreach (bill b in orderedProduct.Values)
            {
                total += moneyOfOneProduct(b);
            }
            return total;
        }
    }
    }

Work/Work/Controllers/CartShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Work.Models;

namespace Work.Controllers
{
    public class CartShopController : Controller
    {
        // GET: CartShop
        public ActionResult Index()
        {
            CartShop gh = Session["cartshop"] as CartShop;
            ViewData["cartlist"] = gh;
            return View();
        }

        public ActionResult Increase(string productID)
        {
            CartShop gh = Session["cartshop"] as CartShop;
            gh.addItem(productID);
            Session["cartshop"] = gh;
            return RedirectToAction("Index");
        }
        public ActionResult Decrease(string productID)
        {
            CartShop gh = Session["cartshop"] as CartShop;
            gh.decrease(productID);
            Session["cartshop"] = gh;
            return RedirectToAction("Index");
        }

        public ActionResult RemoveItem(string productID)
        {
            CartShop gh = Session["cartshop"] as CartShop;
            gh.deleteItem(productID);
            Session["cartshop"] = gh;
            return RedirectToAction("Index");
        }

    }
}

Work/Work/Views/CartShop/Index.cshtml
@using Work.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    CartShop c = ViewData["cartlist"] as CartShop;
    // Retrieve the cart
    var cart = Work.App_Start.SessionConfig.GetCartLits();

    // Check if the cart is not null before accessing its properties or methods
    ViewBag.totalCart = cart?.cartItem() ?? 0;
}


<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="/home/index">Home</a>
                <a class="breadcrumb-item text-dark" href="/product/shop">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @{
                        foreach (bill b in c.orderedProduct.Values)
                        {
                            <tr>
                                <td class="align-middle">
                                    <img src="~/Content/client/@Common.GetImgOfProductByID(b.productID)" alt="" style="width: 50px;">
                                    @Common.GetNameOfProductByID(b.productID)
                                </td>
                                <td class="align-middle">$@b.price</td>
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            @using (Html.BeginForm("Decrease", "CartShop", FormMethod.Post))
                                            {
                                                <button class="btn btn-sm btn-primary btn-minus" value="@b.productID" name="productID">
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            }
                                        </div>
                                        <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="@b.quantity">
                                        <div class="input-group-btn">
                                            @using (Html.BeginForm("Increase", "CartShop", FormMethod.Post))
                                            {
                                                <button class="btn btn-sm btn-primary btn-plus" value="@b.productID" name="productID">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            }
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">$@c.moneyOfOneProduct(b)</td>
                                <td class="align-middle">
                                    @using (Html.BeginForm("RemoveItem", "CartShop", FormMethod.Post))
                                    {
                                        <button class="btn btn-sm btn-danger" value="@b.productID" name="productID">
                                            <i class="fa fa-times"></i>
                                        </button>
                                    }
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            @*<form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>*@
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>$@c.totalOfCartShop()</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$@(@ViewBag.totalCart > 0 ? 2 : 0)</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>$@(c.totalOfCartShop() + (@ViewBag.totalCart > 0 ? 2 : 0))</h5>
                    </div>
                    <a class="btn btn-block btn-primary font-weight-bold my-3 py-3" href="/checkout/index">Proceed To Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->